
#  ENHANCED COMPLETE TRANSCRIPT PIPELINE
# Clean 
# ===========================================

import sys, os, glob, re, torch, concurrent.futures
from google.colab import files
import warnings
warnings.filterwarnings("ignore")

print(" Installing enhanced dependencies...")
!pip install -q transformers torch reportlab accelerate

# IMPORTS
from transformers import pipeline, AutoTokenizer
from reportlab.lib.pagesizes import letter
from reportlab.pdfgen import canvas

print(" Dependencies ready!")

# 1. CLEANING FUNCTION (ENHANCED)
def clean_line(line: str) -> str:
    patterns_to_drop = [
        r"^\s*Transcript generated by", r"^\s*Powered by .*",
        r"^\s*\d{1,2}:\d{2}(:\d{2})?\s*$", r"^\s*Time\s*Stamp.*$",
        r"^\s*\[[0-9:]+\]\s*$", r"^\s*\(\d+\)\s*$"
    ]
    for pat in patterns_to_drop:
        if re.search(pat, line, re.IGNORECASE): return ""
    line = re.sub(r"^\s*(Speaker|Person|User|Assistant)\s*\d*\s*[:\-]?\s*", "", line, re.IGNORECASE)
    line = re.sub(r"[^\w\s\.\,\!\?\:\;\-\'\"]", " ", line)
    line = re.sub(r"\s+", " ", line.strip())
    return line if len(line) > 3 else ""

# 2. UPLOAD & EXTRACT
print("\n UPLOAD YOUR TRANSCRIPT ZIP:")
uploaded = files.upload()
zip_name = list(uploaded.keys())[0]
print(f" Uploaded: {zip_name}")

!rm -rf transcripts_raw transcripts_cleaned summaries
!mkdir -p transcripts_raw transcripts_cleaned summaries

!unzip -q "{zip_name}" -d transcripts_raw
print(" Extracted!")

# 3. CLEAN ALL TRANSCRIPTS
print("\n CLEANING TRANSCRIPTS...")
input_root, output_root = "transcripts_raw", "transcripts_cleaned"
txt_files = glob.glob(os.path.join(input_root, "**", "*.txt"), recursive=True)

for in_path in txt_files:
    rel_path = os.path.relpath(in_path, input_root)
    out_path = os.path.join(output_root, rel_path)
    os.makedirs(os.path.dirname(out_path), exist_ok=True)

    with open(in_path, "r", encoding="utf-8", errors="ignore") as f:
        lines = f.readlines()
    cleaned = [clean_line(l) for l in lines if clean_line(l)]

    with open(out_path, "w", encoding="utf-8") as f:
        f.write("\n".join(cleaned))

cleaned_files = glob.glob(os.path.join(output_root, "**", "*.txt"), recursive=True)
print(f" CLEANED {len(cleaned_files)} transcripts!")
